print('Hello!\tI\'m a\ncomplicated\\interesting\n\”string\”')
print()
print("\ta\tb\tc")
print()
print("\\\\")
print()
print("'")
print()
print("\"\"\"")
print()
print("c:\now\then\this_is_confusing")

