print('Hello!\tI\'m a\ncomplicated\\interesting\n\”string\”')
print()
print("\ta\tb\tc")
print()
print("\\\\")
print()
print("'")
print()
print("\"\"\"")
print()
print("what is going " + str(10 * 2 - 20) + "n here?")

