#!/bin/bash
#
# This pre-commit hook clears output cells in Jupyter notebooks.

# setting bash strict mode
set -o errexit
set -o pipefail
set -o nounset
IFS=$'\n\t'


# functions
function elementIn () {
  local elem="$1"  # Save first argument in a variable
  shift            # Shift all arguments to the left (original $1 gets lost)
  local arr=("$@") # Rebuild the array with rest of arguments
  if printf '%s\n' ${arr[@]+"${arr[@]}"} | grep -q --line-regexp "${elem}"; then
    return 0
  fi
  return 1
}

# what commit we should compare against (initial or HEAD)
if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

CANDIDATE_FILES=()
IPYNB_FILES=()
while IFS='' read -r line; do
	IPYNB_FILES+=( "$line" );
# finding all staged *.ipynb files added, copied, modified or renamed since last commit
done < <(git diff-index --name-only --cached --diff-filter=ACMR "${against}" -- | grep -i \.ipynb$ )
for FILE in ${IPYNB_FILES[@]+"${IPYNB_FILES[@]}"}; do
	echo "Processing file: '$FILE'"
	# execute, then remove tagged outputs and convert to slides in a separate step (otherwise the execute seems to happen last)
    jupyter nbconvert --to notebook --execute --allow-errors --inplace "$FILE"
    jupyter nbconvert --to html --output-dir=lectures/html --SlidesExporter.reveal_scroll=True --TagRemovePreprocessor.enabled=True --TagRemovePreprocessor.remove_all_outputs_tags "remove-output" "$FILE"
    jupyter nbconvert --to slides --output-dir=lectures/html --SlidesExporter.reveal_scroll=True --TagRemovePreprocessor.enabled=True --TagRemovePreprocessor.remove_all_outputs_tags "remove-output" "$FILE"
	jupyter nbconvert --clear-output "$FILE"
	git add $FILE
	HTML="lectures/html/$(basename "${FILE%.*}").html"
	git add $HTML
	SLIDES="lectures/html/$(basename "${FILE%.*}").slides.html"
	git add $SLIDES
	echo "Re-staged ${FILE} and added ${HTML} and ${SLIDES}"
done

exit 0
